# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 563883fc284f7abe3af289d9b2f215fb8376d136af265d6ffbb0b1cd0d66ae9c208ec911f8fe7c91350c5c5c90d632ade5c3de4435bfb9c77f120457abd9c973

test:
  secret_key_base: d7ea92c0c976719ef24d812c382ebf16ac0f000dfafcb32b14fae6f058d60e2822a66bd8fbc3fcd070bb0710640c9577eec254ca1c7b277cab2aa3a2a81b0ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
